---

- name: 拷贝公钥
  copy:
    src: id_rsa.pub
    dest: "/home/vagrant/.ssh/"
    mode: 0600

- name: 拷贝私钥
  copy:
    src: id_rsa
    dest: "/home/vagrant/.ssh/"
    mode: 0600

- name: 设置无密访问
  authorized_key: user=vagrant key="{{ lookup('file', '../files/id_rsa.pub') }}"

- name: 设置java环境变量
  template : src=java.sh.j2 dest=/etc/profile.d/java.sh
  become: yes

- name: 删除原先/etc/hosts中hostname的那行
  lineinfile:
    dest:  /etc/hosts
    state: absent
    regexp: "^127"
  become: yes

- name: Disable selinux
  become: yes
  selinux:
    state: disabled
  notify: Reload systemd

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa {{ item }}
  with_items: "{{ groups['all'] }}"
  register: keyscans

- name: prepare known_hosts
  lineinfile:
    dest=/home/vagrant/.ssh/known_hosts
    create=yes
    state=present
    line="{{ item.stdout }}"
    regexp="^{{ item.item }}"
    owner=vagrant
    group=vagrant
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile:
    dest=/home/vagrant/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner=vagrant
    group=vagrant