---

- name: config hadoop
  template:
    src: "{{item}}-site.xml.j2"
    dest: "/vagrant/tools/hadoop/etc/hadoop/{{item}}-site.xml"
  loop:
    - core
    - hdfs
    - mapred
    - yarn

- name: create data directory
  file: path=/vagrant/tools/hadoop/{{item}}  state=directory
  loop:
    - data
    - data/datanode
    - data/namenode
    - data/journalnode
    - data/tmp

- name: config hadoop-env.sh
  template:
    src: hadoop-env.sh.j2
    dest: /vagrant/tools/hadoop/etc/hadoop/hadoop-env.sh

- name: 配置worker
  template:
    src: workers.j2
    dest: /vagrant/tools/hadoop/etc/hadoop/workers

- name: 设置hadoop环境变量
  template : src=hadoop.sh.j2 dest=/etc/profile.d/hadoop.sh
  become: yes

