---

- name: copy ambari repo...
  copy: src={{item}}  dest=/etc/yum.repos.d/
  become: yes
  loop:
    - ambari.repo
    - ambari-hdp-1.repo

- name: install ntp epel openssl
  shell: rpm -ivh /vagrant/tools/ambari/{{item}} --force
  become: true
  loop:
    - autogen-libopts-5.18-5.el7.x86_64.rpm
    - ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm
    - ntp-4.2.6p5-29.el7.centos.2.x86_64.rpm
    - epel-release-7-11.noarch.rpm
    - openssl-libs-1.0.2k-19.el7.x86_64.rpm
    - openssl-1.0.2k-19.el7.x86_64.rpm
    - unzip-6.0-21.el7.x86_64.rpm

- name: set_time_sync...
  systemd:
    name: ntpd
    state: started
    enabled: yes
  become: yes

- name: set_default_file_perm...
  shell: "enabled=0 && umask 0022 && echo umask 0022 >> /etc/profile"
  become: yes