---
- hosts: all
  become: false
  roles:
    - role: common

- hosts: hadoop
  gather_facts: true
  become: false
  roles:
    - role: hadoop

- hosts: hbase
  gather_facts: true
  become: false
  roles:
    - role: hbase
