---
- hosts: all
  become: false
  roles:
    - role: common

- hosts: zookeeper
  gather_facts: true
  become: false
  roles:
    - role: zookeeper

- hosts: flink
  gather_facts: true
  become: false
  roles:
    - role: flink

- hosts: clickhouse
  gather_facts: true
  become: false
  roles:
    - role: clickhouse