# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [{
   hostname: "host1",
   ip: "192.168.44.11",
   memory: "4096",
   cpus: 2,
   port: 8081,
   promisc: 2,
},{
   hostname: "host2",
   ip: "192.168.44.12",
   memory: "4096",
   cpus: 2,
   port: 9092,
   promisc: 2,
},{
   hostname: "host3",
   ip: "192.168.44.13",
   memory: "4096",
   cpus: 2,
   port: 8083,
   promisc: 2,
},{
   hostname: "host4",
   ip: "192.168.44.14",
   memory: "4096",
   cpus: 2,
   port: 9000,
   promisc: 2,
},{
   hostname: "host5",
   ip: "192.168.44.15",
   memory: "4096",
   cpus: 2,
   port: 8123,
   promisc: 2,
},{
   hostname: "host6",
   ip: "192.168.44.16",
   memory: "4096",
   cpus: 2,
   port: 8089,
   promisc: 2,
}]


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box_check_update = false

  hosts.each_with_index do |host, index|
    config.vm.define host[:hostname] do |node|
      node.vm.hostname = host[:hostname]
      node.vm.network "forwarded_port", guest: host[:port], host: host[:port]
      node.vm.network "private_network", ip: host[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = host[:memory]
        vb.cpus = host[:cpus]
        if host.has_key?(:promisc)
          vb.customize ["modifyvm", :id, "--nicpromisc#{host[:promisc]}", "allow-all"]
        end
        # disable audio, so that the vm doesn't capture the sound / mic
        vb.customize ["modifyvm", :id, "--audio", "none"]
      end
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "../../install/playbooks/kafka-flink-clickhouse.yml"
    ansible.inventory_path = "./inventory"
  end
end

