---
- hosts: clickhouse
  tasks:
    - name: start clickhouse
      service:
        name: "clickhouse-server"
        state: started
  become: yes
  tags: start

- hosts: clickhouse
  tasks:
    - name: stop clickhouse
      service:
        name: "clickhouse-server"
        state: stopped
  become: yes
  tags: stop

- hosts: clickhouse
  tasks:
    - name: restart clickhouse
      service:
        name: "clickhouse-server"
        state: restarted
  become: yes
  tags: restart

- hosts: clickhouse
  tasks:
    - name: server status
      shell: service clickhouse-server status
      become: yes
      register: server_mode

    - name: print status
      debug:
        msg: "{{ server_mode.stdout }}"
  tags: status

