---
- hosts: elasticsearch
  tasks:
    - name: start elasticsearch
      shell: nohup elasticsearch > elasticsearch.log &
  tags: start

- hosts: elasticsearch
  tasks:
    - name: stop elasticsearch
      shell: kill -9 \$(jps | grep Elasticsearch | awk '{print \$1}')
  tags: stop

- hosts: elasticsearch
  tasks:
    - name: jps
      shell: jps
      register: server_mode

    - name: print status
      debug:
        msg: "{{ server_mode.stdout }}"
  tags: status

