---
- hosts: jobmanager
  tasks:
    - name: start flink standalone
      shell: start-cluster.sh
  tags: start-alone

- hosts: jobmanager
  tasks:
    - name: stop flink
      shell: stop-cluster.sh
  tags: stop-alone

- hosts: jobmanager
  tasks:
    - name: start flink yarn
      shell: export HADOOP_CLASSPATH=`hadoop classpath` | yarn-session.sh -n 2 -s 1 -jm 100 -tm 100 -nm test
  tags: start-yarn

- hosts: flink
  tasks:
    - name: jps
      shell: jps
      register: server_mode

    - name: print status
      debug:
        msg: "{{ server_mode.stdout }}"
  tags: status

