---
#### 初始化
- hosts: journalnode
  tasks:
    - name: start journalnode
      shell: /vagrant/tools/hadoop/bin/hdfs --daemon start journalnode
  tags: startjn

- hosts: journalnode
  tasks:
    - name: stop journalnode
      shell: /vagrant/tools/hadoop/bin/hdfs --daemon stop journalnode
  tags: stopjn

- hosts: master
  tasks:
    - name: format main_namenode
      shell: /vagrant/tools/hadoop/bin/hdfs namenode -format
      register: format_info

    - name: print format_info
      debug:
        msg: "{{ format_info.stdout }}"
  tags: formatnn

- hosts: master
  tasks:
    - name: start main_namenode
      shell: /vagrant/tools/hadoop/sbin/hadoop-daemon.sh start namenode

    - name: jps
      shell: jps
      register: mainnn_info

    - name: print mainnn_info
      debug:
        msg: "{{ mainnn_info.stdout }}"
  tags: startnn

- hosts: standby_namenode
  tasks:
    - name: sync standby_namenode
      shell: /vagrant/tools/hadoop/bin/hdfs namenode -bootstrapStandby
  tags: syncnn

- hosts: standby_namenode
  tasks:
    - name: start standby_namenode
      shell: /vagrant/tools/hadoop/sbin/hadoop-daemon.sh start namenode

    - name: jps
      shell: jps
      register: snn_info

    - name: print snn_info
      debug:
        msg: "{{ snn_info.stdout }}"
  tags: startsnn

- hosts: master
  tasks:
    - name: format zkfc
      shell: /vagrant/tools/hadoop/bin/hdfs zkfc -format
      register: format_zkfc

    - name: print format_zkfc
      debug:
        msg: "{{ format_zkfc.stdout }}"
  tags: formatzkfc

### 维护命令
- hosts: master
  tasks:
    - name: start dfs
      shell: /vagrant/tools/hadoop/sbin/start-dfs.sh
  tags: start

- hosts: master
  tasks:
    - name: restart dfs
      shell: /vagrant/tools/hadoop/sbin/restart-dfs.sh
  tags: restart

- hosts: master
  tasks:
    - name: stop dfs
      shell: /vagrant/tools/hadoop/sbin/stop-dfs.sh
  tags: stop

- hosts: all
  tasks:
    - name: jps
      shell: jps
      register: jps_mode

    - name: print jps_mode
      debug:
        msg: "{{ jps_mode.stdout }}"
  tags: status

