---
#### 初始化

- hosts: namenode
  tasks:
    - name: format namenode
      shell: hdfs namenode -format mycluster
      register: format_info

    - name: print format_info
      debug:
        msg: "{{ format_info.stdout }}"
  tags: formatnn

### 维护命令
- hosts: namenode
  tasks:
    - name: start dfs
      shell: start-dfs.sh
    - name: start yarn
      shell: start-yarn.sh
    - name: start job history
      shell: mapred --daemon start historyserver
  tags: start

- hosts: namenode
  tasks:
    - name: restart dfs
      shell: restart-dfs.sh
    - name: restart yarn
      shell: restart-yarn.sh
  tags: restart

- hosts: namenode
  tasks:
    - name: stop dfs
      shell: stop-dfs.sh
    - name: stop yarn
      shell: stop-yarn.sh
  tags: stop

- hosts: all
  tasks:
    - name: jps
      shell: jps
      register: jps_mode

    - name: print jps_mode
      debug:
        msg: "{{ jps_mode.stdout }}"
  tags: status

