---
- hosts: all
  become: false
  roles:
    - role: common
  tags:
    - common

- hosts: zookeeper
  gather_facts: true
  become: false
  roles:
    - role: zookeeper
  tags:
    - zookeeper

#- hosts: all
#  gather_facts: true
#  become: false
#  roles:
#    - role: hadoop
#  tags:
#    - hadoop

- hosts: storm
  gather_facts: true
  become: false
  roles:
    - role: storm
  tags:
    - storm

- hosts: kafka
  gather_facts: true
  become: false
  roles:
    - role: kafka
  tags:
    - kafka