---
- hosts: all
  become: false
  roles:
    - role: common
  tags:
    - common

- hosts: hadoop
  gather_facts: true
  become: false
  roles:
    - role: hadoop-ha
  tags:
    - hadoop-ha

- import_playbook: playbooks/ambari.yml
  tags:
    - ambari

- import_playbook: playbooks/clickhouse.yml
  tags:
    - clickhouse

- import_playbook: playbooks/elasticsearch.yml
  tags:
    - elasticsearch

- import_playbook: playbooks/flink.yml
  tags:
    - flink

- import_playbook: playbooks/hadoop.yml
  tags:
    - hadoop

- import_playbook: playbooks/hbase.yml
  tags:
    - hbase

- import_playbook: playbooks/kafka.yml
  tags:
    - kafka

- import_playbook: playbooks/kafka-flink-clickhouse.yml
  tags:
    - kafka-flink-clickhouse

- import_playbook: playbooks/storm.yml
  tags:
    - storm

- import_playbook: playbooks/zookeeper.yml
  tags:
    - zookeeper





